{
 "title": "GRDF",
 "time": { "from": "now-2y", "to": "now+1y" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "pce",
    "label": "PCE",
    "query": "import \"date\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: 1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> keep(columns:[\"pce\"])\r\n  |> group()"
   },
   { "name": "measure_unit", "label": "Unité", "query": "M3,kWh,€" }
  ]
 },
 "panels": [
  {
   "title": "Mesuré",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "# Gazpar\n\n  $pce\n  \n  <img src=\"https://nc.airvb.com/index.php/s/Hk3JRpmwpJg2oJE/preview\" width=\"100%\">\n\n           "
   },
   "targets": [
    {
     "query": "from(bucket: \"gazpar\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gazpar_informative_measure\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy_kWh\")\r\n  |> drop(columns:[\"year\",\"month\",\"pce\",\"pce_alias\",\"_measurement\",\"_field\"])\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "J-6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -7d, stop: -6d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\",\"weekday_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"actual\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "J-5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -6d, stop: -5d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\",\"weekday_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"actual\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "J-4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -5d, stop: -4d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\",\"weekday_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"actual\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "J-3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -4d, stop: -3d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\",\"weekday_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"actual\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "J-2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -3d, stop: -2d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\",\"weekday_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"actual\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "J-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -2d, stop: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\",\"weekday_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"actual\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Prix au kWh",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prix_kwh\")\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\"])\r\n  |> group(columns: [\"prix_kwh\"], mode: \"by\")\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -4y, stop: -1d)\r\n  |> filter(fn: (r) => r[\"year\"] == string(v: date.year(t: -3y)))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n    |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n\r\n  |> drop(columns:[\"weekday_name\",\"weekday_no\",\"month_name\",\"pce\",\"pce_alias\",\"month\",\"month_short\",\"_measurement\",\"type\",\"mois_num\"])\r\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Prix fixe journalier",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prix_fixe\")\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\"])\r\n  |> group(columns: [\"prix_fixe\"], mode: \"by\")\r\n  |> last()\r\n\r\n  "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -3mo, stop: -1d)\r\n  |> filter(fn: (r) => r[\"mois_num\"] == string(v: date.month(t: -1d)))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> drop(columns:[\"year\",\"weekday_name\",\"weekday_no\",\"pce\",\"pce_alias\",\"month\",\"month_short\",\"_measurement\",\"type\"])\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -6mo, stop: -0mo)\r\n  |> filter(fn: (r) => r[\"mois_num\"] == string(v: date.month(t: -1mo)))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> drop(columns:[\"year\",\"weekday_name\",\"weekday_no\",\"pce\",\"pce_alias\",\"month\",\"month_short\",\"_measurement\",\"type\",\"moins_num\"])\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Tendance",
   "type": "stat",
   "description": "Tendance par rapport au mois passé sur la même période",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\n// Get last measure date of the current month\r\nyesterday = date.truncate(t: -1d, unit: 1d)\r\nyesterday_m1 = date.truncate(t: -1mo, unit: 1d)\r\n\r\n// Get data\r\ndata = from(bucket: \"$bucket\")\r\n  |> range(start: -2mo, stop: -0mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> drop(columns:[\"year\",\"weekday_name\",\"month_name\",\"month_short\", \"weekday_no\",\"pce\",\"pce_alias\",\"_measurement\",\"type\"])\r\n  |> group()\r\n\r\n// Set dataset based on current month\r\nm0 = data\r\n  |> filter(fn: (r) => r[\"mois_num\"] == string(v: date.month(t: yesterday)))\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with m0: r._value }))\r\n  |> map(fn: (r) => ({ r with key: \"A\" }))\r\n  |> keep(columns:[\"m0\",\"key\"])\r\n  //|> yield(name: \"current\")\r\n\r\n// Set dataset based on previous month\r\nm1 = data\r\n  |> range(start: -2mo, stop: yesterday_m1)\r\n  |> filter(fn: (r) => r[\"mois_num\"] == string(v: date.month(t: yesterday_m1)))\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with m1: r._value }))\r\n  |> map(fn: (r) => ({ r with key: \"A\" }))\r\n  |> keep(columns:[\"m1\",\"key\"])\r\n  //|> yield(name: \"previous\")\r\n\r\n// Join datasets and calculate percentage\r\njoin(\r\n  tables: {m1: m1, m0: m0},\r\n  on: [\"key\"],\r\n  method: \"inner\"\r\n)\r\n|> map(fn: (r) => ({ r with \r\n  trend:  \r\n  if not exists r[\"m1\"] or r[\"m1\"] == 0.0 then 0.0\r\n  else ((r[\"m0\"]-r[\"m1\"]) / r[\"m1\"] )*100.0\r\n  }))\r\n|> keep(columns:[\"trend\"])\r\n|> yield(name: \"trend\")"
    }
   ]
  },
  {
   "title": "Consommation journalière / T° C(30 derniers jours)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "data = from(bucket: \"$bucket\")\r\n  |> range(start: -1mo, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> keep(columns:[\"_time\",\"_value\",\"_field\"])\r\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\r\n  |> timeShift(duration: -1d, columns: [\"_time\"])\r\n  |> yield(name: \"data\")\r\n  \r\n\r\nminData = data\r\n|> min()\r\n|> yield(name: \"min\")\r\n\r\n\r\nmaxData = data\r\n|> max()\r\n|> yield(name: \"max\")\r\n"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Température locale (°C)\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -3y, stop: -1d)\r\n  |> filter(fn: (r) => r[\"year\"] == string(v: date.year(t: -2y)))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n    |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n\r\n  |> drop(columns:[\"weekday_name\",\"weekday_no\",\"month_name\",\"pce\",\"pce_alias\",\"month\",\"month_short\",\"_measurement\",\"type\",\"mois_num\"])\r\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tendance",
   "type": "stat",
   "description": "Tendance par rapport à l'année dernière sur la même période",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\n// Get last measure date of the current month\r\nyesterday = date.truncate(t: -1d, unit: 1d)\r\nyesterday_m1 = date.truncate(t: -1y, unit: 1d)\r\nyesterday_m2 = date.truncate(t: -2y, unit: 1d)\r\n\r\n// Get data\r\ndata = from(bucket: \"$bucket\")\r\n  |> range(start: -3y, stop: -0mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Volume consommé (m3)\")\r\n  |> drop(columns:[\"month\",\"weekday_name\",\"month_name\",\"weekday_no\",\"pce_alias\", \"pce\",\"month_short\",\"_measurement\",\"type\",\"mois_num\",\"_start\",\"_stop\"])\r\n  |> group()\r\n  //|> yield(name: \"alpha\")\r\n\r\n// Set dataset based on current year AN\r\nm0 = data\r\n  |> filter(fn: (r) => r[\"year\"] == string(v: date.year(t: yesterday)))\r\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with m0: r._value }))\r\n  //|> map(fn: (r) => ({ r with key: string(v: date.year(t: yesterday)) }))\r\n  |> map(fn: (r) => ({ r with key: \"A\" }))\r\n  |> keep(columns:[\"m0\",\"key\"])\r\n  //|> yield(name: string(v: date.year(t: yesterday)))\r\n\r\n// Set dataset based on previous year AN-1 \r\nm1 = data\r\n  |> range(start: -2y, stop: yesterday_m1)\r\n  |> filter(fn: (r) => r[\"year\"] == string(v: date.year(t: yesterday_m1)))\r\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with m1: r._value }))\r\n  //|> map(fn: (r) => ({ r with key: string(v: date.year(t: yesterday_m1))}))\r\n  |> map(fn: (r) => ({ r with key: \"A\" }))\r\n  |> keep(columns:[\"m1\",\"key\"])\r\n  //|> yield(name: string(v: date.year(t: yesterday_m1)))\r\n\r\n// Set dataset based AN-2\r\n\r\nm2 = data\r\n  |> range(start: -3y, stop: yesterday_m2)\r\n  |> filter(fn: (r) => r[\"year\"] == string(v: date.year(t: yesterday_m2)))\r\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with m2: r._value }))\r\n  |> map(fn: (r) => ({ r with key: \"A\" }))\r\n  //|> map(fn: (r) => ({ r with key: string(v: date.year(t: yesterday_m2))}))\r\n  |> keep(columns:[\"m2\",\"key\"])\r\n  //|> yield(name: string(v: date.year(t: yesterday_m2)))\r\n\r\n\r\n  // Join datasets and calculate percentage\r\njoin(\r\n  tables: {m2: m2, m1: m1},\r\n  on: [\"key\"],\r\n  method: \"inner\"\r\n)\r\n|> map(fn: (r) => ({ r with \r\n  trend:  \r\n  if not exists r[\"m2\"] or r[\"m2\"] == 0.0 then 0.0\r\n  else ((r[\"m1\"]-r[\"m2\"]) / r[\"m2\"] )*100.0\r\n  }))\r\n|> keep(columns:[\"trend\"])\r\n|> yield(name: \"trend\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -2y, stop: -1d)\r\n  |> filter(fn: (r) => r[\"year\"] == string(v: date.year(t: -1y)))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n    |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n\r\n  |> drop(columns:[\"weekday_name\",\"weekday_no\",\"month_name\",\"pce\",\"pce_alias\",\"month\",\"month_short\",\"_measurement\",\"type\",\"mois_num\"])\r\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tendance",
   "type": "stat",
   "description": "Tendance par rapport à l'année dernière sur la même période",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\n// Get last measure date of the current month\r\nyesterday = date.truncate(t: -1d, unit: 1d)\r\nyesterday_m1 = date.truncate(t: -1y, unit: 1d)\r\n\r\n// Get data\r\ndata = from(bucket: \"$bucket\")\r\n  |> range(start: -2y, stop: -0mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n  |> drop(columns:[\"month\",\"weekday_name\",\"month_name\",\"weekday_no\",\"pce_alias\", \"month_short\",\"_measurement\",\"type\",\"mois_num\"])\r\n  |> group()\r\n\r\n// Set dataset based on current year\r\nm0 = data\r\n  |> filter(fn: (r) => r[\"year\"] == string(v: date.year(t: yesterday)))\r\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with m0: r._value }))\r\n  |> map(fn: (r) => ({ r with key: \"A\" }))\r\n  |> keep(columns:[\"m0\",\"key\"])\r\n  //|> yield(name: \"current\")\r\n\r\n// Set dataset based on previous year\r\nm1 = data\r\n  |> range(start: -2y, stop: yesterday_m1)\r\n  |> filter(fn: (r) => r[\"year\"] == string(v: date.year(t: yesterday_m1)))\r\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with m1: r._value }))\r\n  |> map(fn: (r) => ({ r with key: \"A\" }))\r\n  |> keep(columns:[\"m1\",\"key\"])\r\n  //|> yield(name: \"previous\")\r\n\r\n// Join datasets and calculate percentage\r\njoin(\r\n  tables: {m1: m1, m0: m0},\r\n  on: [\"key\"],\r\n  method: \"inner\"\r\n)\r\n|> map(fn: (r) => ({ r with \r\n  trend:  \r\n  if not exists r[\"m1\"] or r[\"m1\"] == 0.0 then 0.0\r\n  else ((r[\"m0\"]-r[\"m1\"]) / r[\"m1\"] )*100.0\r\n  }))\r\n|> keep(columns:[\"trend\"])\r\n|> yield(name: \"trend\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: -13mo, stop: -1d)\r\n  |> filter(fn: (r) => r[\"year\"] == string(v: date.year(t: -1d)))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n    |> filter(fn: (r) => \r\n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\r\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \r\n    else r[\"_field\"] == \"Volume consommé (m3)\"\r\n    )\r\n\r\n  |> drop(columns:[\"weekday_name\",\"weekday_no\",\"month_name\",\"pce\",\"pce_alias\",\"month\",\"month_short\",\"_measurement\",\"type\",\"mois_num\"])\r\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Par mois  2021 ($measure_unit)",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 1, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"$bucket\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\n  |> filter(fn: (r) => \n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \n    else r[\"_field\"] == \"Volume consommé (m3)\"\n    )\n  |> filter(fn: (r) => r[\"year\"] == \"2021\")\n\n\n  |> group(columns: [\"month\",\"year\"])\n\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Par mois 2022 ($measure_unit)",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"$bucket\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\n  |> filter(fn: (r) => \n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \n    else r[\"_field\"] == \"Volume consommé (m3)\"\n    )\n  |> filter(fn: (r) => r[\"year\"] == \"2022\")\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Par mois 2023  ($measure_unit)",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"$bucket\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\n  |> filter(fn: (r) => \n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \n    else r[\"_field\"] == \"Volume consommé (m3)\"\n    )\n  |> filter(fn: (r) => r[\"year\"] == \"2023\")\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Moyenne jour ($measure_unit)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"$bucket\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\n  |> filter(fn: (r) => \n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \n    else r[\"_field\"] == \"Volume consommé (m3)\"\n    )\n  |> filter(fn: (r) => r[\"year\"] == \"2021\")\n  //|> group(columns: [\"month\",\"year\"])\n  |> group(columns: [\"year\"])\n  //|> sum(column: \"_value\")\n  |> mean(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Moyenne jour ($measure_unit)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"$bucket\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\n  |> filter(fn: (r) => \n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \n    else r[\"_field\"] == \"Volume consommé (m3)\"\n    )\n  |> filter(fn: (r) => r[\"year\"] == \"2022\")\n  //|> group(columns: [\"month\",\"year\"])\n  |> group(columns: [\"year\"])\n  //|> sum(column: \"_value\")\n  |> mean(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Moyenne jour ($measure_unit)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"$bucket\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\n  |> filter(fn: (r) => \n    if \"$measure_unit\" == \"kWh\" then r[\"_field\"] == \"Energie consommée (kWh)\"\n    else if  \"$measure_unit\" == \"€\" then r[\"_field\"] == \"cout\"  \n    else r[\"_field\"] == \"Volume consommé (m3)\"\n    )\n  |> filter(fn: (r) => r[\"year\"] == \"2023\")\n  //|> group(columns: [\"month\",\"year\"])\n  |> group(columns: [\"year\"])\n  //|> sum(column: \"_value\")\n  |> mean(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Analyse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Consommation (kwh) et coût (€) par mois",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "query": "from(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cout\")\r\n  |> drop(columns:[\"month\",\"year\",\"weekday_no\",\"weekday_name\",\"pce\",\"pce_alias\",\"month_name\",\"month_short\",\"_measurement\",\"mois_num\"])\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> timeShift(duration: -1mo, columns: [\"_time\"])\r\n  |> yield(name: \"sum\")"
      },
      {
       "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mesuré\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Energie consommée (kWh)\")\n  |> drop(columns:[\"month\",\"year\",\"weekday_no\",\"weekday_name\",\"pce\",\"pce_alias\",\"month_name\",\"month_short\",\"_measurement\",\"mois_num\"])\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\n  |> timeShift(duration: -1mo, columns: [\"_time\"])\n  |> yield(name: \"sum\")"
      }
     ]
    }
   ]
  }
 ]
}